// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbvxdntjyatvcpaxkmrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtidnhkbnRqeWF0dmNwYXhrbXJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5MDAzMTAsImV4cCI6MjA1NjQ3NjMxMH0.lDe0h88k7H5qxcwuYLJDcpmYnA0l2OCsIFWmwAP-Xo0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);